# This is a basic workflow to help you get started with Actions

name: Deploy node.js CORE

on:
    push:
      branhces:
      -master

env:
    AZURE_WEBAPP_NAME:currencyconverterinjavascript
    AZURE_WEBAPP_PATH:'.'
    NODE_VERSION: 'v8.16.0'

    jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout

    - name: Login via Azure CLI
       uses: azure/login@v1
      
      with:
        creds:${{ secrets.AZURE_CREDENTIALS }}
        
    - name: SETUP .js CORE
      uses:actions/setup-node@v2
      with:
        node-version: ${{ env.NODE_VERSION }}

    -name:nodejs build+publish
    run:
    nodejs build --configuration release
    nodejs publish -c Release -o '${{ env.AZURE_WEBAPP_PATH}}/myapp'

    -name: Deploy to App Service
    uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        package: '${{ env.AZURE_WEBAPP_PATH}}/myapp'
